//
// Created by Stefan on 26.04.2026.
//

#pragma once

#define GUI_DEBUG 1

#define GUI_DEBUG_PROCESS_DEBUG 0
#define GUI_DEBUG_RENDER 0
#define GUI_DEBUG_ACCUMULATE_MESHES 0
#define GUI_DEBUG_TRACE_DRAGGING 0
#define GUI_DEBUG_OBSERVE_ELEMENT_UPDATE 0
#define GUI_DEBUG_OBSERVE_ELEMENT_PLACE_CHILDREN "null"